# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.3
loom_version=1.17.17
fabric_api_version=0.145.1+26.1
flk_version=1.13.13+kotlin.2.4.10
moulconfig_version=4.7.2
modmenu_version=18.0.0
# Mod Properties
mod_version=1.5.2
maven_group=fr.augma
archives_base_name=AugmaSkyblockFixes
